### ISSUE TITLE
Make Current server view to react

### ISSUE THREAD

**Issue by seo2im** [seo2im/42Static#3]
## Make Current server view to react
<feature>
view환경 리엑트로 변경, 다만 디자인 단계만 신경쓸 것.(서버 통신 X)

### Todo list
- [x] Login Page 생성
- [x] Main Page 생성
- [x] userNum Page 생성(그래프 X)
- [x] cluster In Out page생성(그래프 X)
